"""remove_graph_extraction

Revision ID: 0a67e207587c
Revises: 6b075f28d44b
Create Date: 2026-07-26 18:57:07.105721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a67e207587c'
down_revision: Union[str, Sequence[str], None] = '6b075f28d44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_constraint(op.f('documents_companion_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'companion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('companion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_companion_id_fkey'), 'documents', 'companions', ['companion_id'], ['id'])
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('node_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('node_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], name=op.f('knowledge_nodes_source_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('knowledge_nodes_source_document_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('knowledge_nodes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_nodes_pkey'))
    )
    op.create_index(op.f('ix_knowledge_nodes_node_name'), 'knowledge_nodes', ['node_name'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('evidence_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], name=op.f('knowledge_edges_source_node_id_fkey')),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], name=op.f('knowledge_edges_target_node_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('knowledge_edges_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_edges_pkey'))
    )
    # ### end Alembic commands ###
