"""add companion_id to documents

Revision ID: 23de61df1a8f
Revises: f3ae9641af5b
Create Date: 2026-06-29 16:25:30.634209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23de61df1a8f'
down_revision: Union[str, Sequence[str], None] = 'f3ae9641af5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('conversations', sa.Column('tavus_conversation_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'tavus_conversation_id')

    # ### end Alembic commands ###
