"""Add duration_seconds to Conversation

Revision ID: 52ad84b0589c
Revises: baf71c07547c
Create Date: 2026-07-14 13:50:53.341886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ad84b0589c'
"""Add duration_seconds to Conversation

Revision ID: 52ad84b0589c
Revises: baf71c07547c
Create Date: 2026-07-14 13:50:53.341886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ad84b0589c'
down_revision: Union[str, Sequence[str], None] = 'baf71c07547c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('duration_seconds', sa.Integer(), server_default='0', nullable=False))
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'duration_seconds')
    # ### end Alembic commands ###
