"""add new tables

Revision ID: 68db4cda30ee
Revises: 95b7ea59eadc
Create Date: 2026-06-23 10:22:07.541681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68db4cda30ee'
down_revision: Union[str, Sequence[str], None] = '95b7ea59eadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_node_name'), 'knowledge_nodes', ['node_name'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_knowledge_nodes_node_name'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
