"""add tavus fields to companions

Revision ID: 95b7ea59eadc
Revises: 8293033c84f0
Create Date: 2026-06-22 17:42:05.513763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b7ea59eadc'
down_revision: Union[str, Sequence[str], None] = '8293033c84f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companions', sa.Column('avatar_provider', sa.String(length=50), nullable=True))
    op.add_column('companions', sa.Column('tavus_replica_id', sa.String(length=255), nullable=True))
    op.add_column('companions', sa.Column('tavus_persona_id', sa.String(length=255), nullable=True))
    op.alter_column('companions', 'persona',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('companions', 'voice_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companions', 'voice_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('companions', 'persona',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('companions', 'tavus_persona_id')
    op.drop_column('companions', 'tavus_replica_id')
    op.drop_column('companions', 'avatar_provider')
    # ### end Alembic commands ###
