"""add_tavus_persona_id

Revision ID: baf71c07547c
Revises: 983ea0cb9631
Create Date: 2026-06-30 23:32:57.194174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf71c07547c'
down_revision: Union[str, Sequence[str], None] = '983ea0cb9631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('tavus_persona_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'tavus_persona_id')
    # ### end Alembic commands ###
