"""add companion_id to documents

Revision ID: f3ae9641af5b
Revises: 983ea0cb9631
Create Date: 2026-06-25 11:58:13.308760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ae9641af5b'
down_revision: Union[str, Sequence[str], None] = '983ea0cb9631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('companion_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'documents', 'companions', ['companion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'companion_id')
    # ### end Alembic commands ###
